import Head from "next/head";
import GridPattern from "~/components/ui/grid-pattern";
import { DefinitionPage } from "~/features/definition/pages";
import { QuizPage } from "~/features/quiz/pages";

export default function QuizPages() {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <title>Quiz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/kalkuluslogo.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-grow dark:bg-darkBg dark:text-white">
        <GridPattern className="-z-10" width={100} height={100} opacity={0.6} />
        <QuizPage />
      </main>
    </>
  );
}
