import { Grid } from "lucide-react";
import Head from "next/head";
import GridPattern from "~/components/ui/grid-pattern";
import { Marque } from "~/components/ui/Marque";
import { DefinitionPage } from "~/features/definition/pages";
import { FormulaPages } from "~/features/formulas/pages";
import { GraphPage } from "~/features/graph/pages";
import { GuidesPage } from "~/features/guides/pages";
import MenuPage from "~/features/menu/pages/MenuPage";
import { MessagePage } from "~/features/message/pages/MessagePages";
import { PointSearch } from "~/features/points/pages";
import { ProfilePage } from "~/features/profile/pages";
import { TypesGrafikPage } from "~/features/type/pages";
import PageContainer from "~/layout/PageContainer";
import { api } from "~/utils/api";

export default function UserPage() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <title>User Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        <DefinitionPage />
        <FormulaPages />
        <PointSearch />
        <GraphPage />
        <GuidesPage />
        <ProfilePage />
        <MessagePage />
      </PageContainer>
    </>
  );
}
